### ISSUE TITLE
Webservice fails to load in offline mode

### ISSUE THREAD

**Issue by habeebq** [causalens/dara#115]
I am working on a machine that does not have internet access.
When I load open the web address in a browser, it fails to load js packages from unpkg.com and code.jquery.com
Is there a way to configure it to load assets from a local location?

**Comment by krzysztof-causalens** [comment]
Hello,
Thanks for reporting the issue. Unfortunately offline development is not a use case Dara was developed in mind with.

Longer term we do have plans to do away with reliance on CDNs for the default run mode (which is aiming to not require `Node`) which will in turn make it easier to develop without internet access.

For the short term I can provide a few workarounds for the time being:

1. If using `Node` (v16 at the minimum) is an option, you can run your `Dara` app with `dara start --production`. This will install (you will need internet access at this point) and bundle all the JS/CSS assets. Subsequent runs will not require internet access as the bundle will already be stored in your output folder (i.e. `./dist`). Dara will only attempt to re-install the packages if a new package is picked up.
2. Alternatively - I appreciate this is not a pretty or simple solution -  you can change the paths in dara's source code to point to a local bundle rather than a CDN. The location of the file will likely be `(/path/to/your/venv/lib/python3.x/site-packages/)dara/core/jinja/index_autojs.html`. This is the index.html file served when running in the default mode. 
The change you'd have to make there would be:

a) replace the `<script>` tags from pointing to remote CDNs to point to a local file:
```html
<!-- before -->
<script crossorigin src="https://unpkg.com/react@18.2.0/umd/react.development.js"></script>
<!-- after -->
<script src="react.development.js"></script>
```
b) download those files and place them in your output folder (default `./dist`)

In either case there will be limitations, e.g. the `bokeh` component always uses a CDN bundle which is loaded when you first load it, so you'd have to use other plotting libraries.
I would recommend the first solution if installing Node is an option as it should be pretty straightforward.

I hope this helps :)

**Comment by habeebq** [comment]
Much appreciated. The situation is a bit more complex as I did have to install everything in docker container, but I suspect I can build the container on a different network, and allow it to get the assets at build time.
I did consider editing the source files, but I'd have to automate that too when the container is built.
This will definitely help.

**Comment by krzysztof-causalens** [comment]
I see, yeah if you're building a container it makes sense to go with the Node approach and build assets ahead of time. FYI the `dara start` command also has a `--docker` flag, which assumes assets are already present and ensures it won't attempt to reinstall/rebuild them again - it might be helpful in this scenario. 

You can build assets ahead of time by either running the `dara start --production` once (probably easiest) or manually calling into the internals in `dara.core.js_tooling.js_utils` in a script.
The `js_utils` module provides all the utilities to achieve that, check out the code there if that's something that solves your needs - it should be heavily commented and self-explanatory.

I'll close the issue for now, thanks for checking out Dara.
